spring:
  profiles:
    active: db , admin
  security:
    user:
      name: adminwyh
      password: wyh247


server:
  port: 8081


image:
  path: D:\Projects\ideaProjects\jy\jy-blog-admin-api\src\main\resources\static\image\




